### PR TITLE
Swift 4 + Objective-C changes

### PR DESCRIPTION
**Pull request by rauldudu**

### CODE REVIEW

**Comment by isuda** [comment]
That seems like a lot of work. Are we going to have to keep rewriting this thing every time a new version of Swift comes out ????

**Comment by rauldudu** [comment]
I think it seems a lot because we removed code that we won't need anymore since we're dropping support for iOS lower than 10.

But you're right Swift 4 broke it anyways :P

It was complaining about the @objc annotations and swizzling inexistent methods.

**Comment by dpogue** [comment]
We should also bump the plugin major version, and say that it depends on a newer version of Cordova...

**Comment by rauldudu** [comment]
Should be good to go

**Pull request merged**
